
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // 공개 API 빌드에는 DB가 필요 없다. migration/보존 스크립트 실행 시 실제 값을 설정한다.
    url: process.env.DATABASE_URL || "mysql://unused:unused@127.0.0.1:3306/unused",
  },
});
